language: python
python:
{% for version in cookiecutter.python_versions %}
- '{{ version }}'
{% endfor%}
install:
- pip install --upgrade pip
- pip install .[dev]
before_script:
- flake8 {{ cookiecutter.project_package }}
- flake8 tests
script: pytest tests
deploy:
  provider: pypi
  user: {{ cookiecutter.github_username }}
  password:
    secure: "This needs to be replaced by running `travis-encrypt` from pip"
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    python: {{ cookiecutter.python_deploy_version }}
